/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoicesRouteImport } from './routes/voices'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as AgentConfigRouteImport } from './routes/agent-config'
import { Route as IndexRouteImport } from './routes/index'

const VoicesRoute = VoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentConfigRoute = AgentConfigRouteImport.update({
  id: '/agent-config',
  path: '/agent-config',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-config': typeof AgentConfigRoute
  '/jobs': typeof JobsRoute
  '/providers': typeof ProvidersRoute
  '/voices': typeof VoicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-config': typeof AgentConfigRoute
  '/jobs': typeof JobsRoute
  '/providers': typeof ProvidersRoute
  '/voices': typeof VoicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-config': typeof AgentConfigRoute
  '/jobs': typeof JobsRoute
  '/providers': typeof ProvidersRoute
  '/voices': typeof VoicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent-config' | '/jobs' | '/providers' | '/voices'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent-config' | '/jobs' | '/providers' | '/voices'
  id: '__root__' | '/' | '/agent-config' | '/jobs' | '/providers' | '/voices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentConfigRoute: typeof AgentConfigRoute
  JobsRoute: typeof JobsRoute
  ProvidersRoute: typeof ProvidersRoute
  VoicesRoute: typeof VoicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voices': {
      id: '/voices'
      path: '/voices'
      fullPath: '/voices'
      preLoaderRoute: typeof VoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-config': {
      id: '/agent-config'
      path: '/agent-config'
      fullPath: '/agent-config'
      preLoaderRoute: typeof AgentConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentConfigRoute: AgentConfigRoute,
  JobsRoute: JobsRoute,
  ProvidersRoute: ProvidersRoute,
  VoicesRoute: VoicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
